image: node:latest

variables:
  ENV_CI: "CI/CD"
  ENV_TEST: "test"

before_script:
  - echo 'Install dependencies'
  - npm install
  
cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
  - echo 'Build application'
  - npm run build
  artifacts:
    paths:
      - build/

deploy-discovery:
  stage: deploy
  needs:
    - job: build
      artifacts: true
  script:
  - echo 'Run discovery server'
  - NODE_ENV=$ENV_CI npm start -w discovery

deploy-peer:
  stage: deploy
  needs:
    - job: build
      artifacts: true
  script:
  - echo 'Run discovery server'
  - NODE_ENV=$ENV_CI npm start -w peer

test-discovery:
  stage: test
  allow_failure: true
  script:
    - echo 'Run tests of discovery server'
    - NODE_ENV=$ENV_TEST npm test -w discovery

test-peer:
  stage: test
  allow_failure: true
  script:
    - echo 'Run tests of peer'
    - NODE_ENV=$ENV_TEST npm test -w peer

lint:
  stage: test
  script:
    - echo 'Run lint'
    - npm run lint
