name: CI/CD Workflow

on:
  push:
    branches:
      - master
      - develop
      - 'feature_*'
      - migration/github

  pull_request:

env:
  ENV_CI: 'CI/CD'
  ENV_TEST: 'test'
  MONGO_DB: 'mongodb://mongo:27017/cluedo'
  MONGO_DB_TEST: 'mongodb://mongo:27017/cluedo-test'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Install dependencies
        run: |
          npm install
          npm run install:peer-ui

      - name: Cache node dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules/
            peer/ui/node_modules/
          key: ${{ runner.os }}-node_modules

      - name: Build application
        run: npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: build/

  deploy-discovery:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore node dependencies
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules/
            peer/ui/node_modules/
          key: ${{ runner.os }}-node_modules

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: build/

      - name: Run discovery server
        run: ENV_CI=CI/CD npm start -w discovery

  deploy-peer:
    runs-on: ubuntu-latest
    needs: build
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore node dependencies
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules/
            peer/ui/node_modules/
          key: ${{ runner.os }}-node_modules

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: build/

      - name: Run peer
        run: MONGODB_ADDRESS=mongodb://localhost:27017/cluedo ENV_CI=CI/CD npm start -w peer

  test-discovery:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore node dependencies
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules/
            peer/ui/node_modules/
          key: ${{ runner.os }}-node_modules

      - name: Run tests of discovery server
        run: |
          NODE_ENV=test npm test -w discovery

  test-peer:
    runs-on: ubuntu-latest
    needs: build
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore node dependencies
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules/
            peer/ui/node_modules/
          key: ${{ runner.os }}-node_modules

      - name: Run tests of peer
        run: |
          MONGODB_ADDRESS=mongodb://localhost:27017/cluedo-test NODE_ENV=test npm test -w peer

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore node dependencies
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules/
            peer/ui/node_modules/
          key: ${{ runner.os }}-node_modules

      - name: Run lint
        run: npm run lint
